name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: before
        run: |
          ls -lt /usr/local/lib
          sudo du -sh /usr/local

      - name: Macports 0
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
           wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
           sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /

      - name: Install dependencies
        run: |
          export PATH="/opt/local/bin:$PATH" 

          sudo port install glib2-devel gtk3 meson
          wget https://gitlab.com/virt-viewer/virt-viewer/-/archive/v11.0/virt-viewer-v11.0.tar.gz
          tar -xzf virt-viewer-v11.0.tar.gz
          cd virt-viewer-v11.0
          export PKG_CONFIG_PATH="/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig"
          meson build
          cd build
          meson install
          pwd
          ls -l /opt/local/lib
          chmod +x ../../fix.sh
          ../../fix.sh

      - name: Compress remote-viewer
        if: steps.cache-remote-viewer.outputs.cache-hit != 'true'
        run: |
          ./virt-viewer-v11.0/build/src/remote-viewer --version
          tar cf remote-viewer-${{ matrix.arch }}.tgz virt-viewer-v11.0/build/libs virt-viewer-v11.0/build/src

      - name: Upload remote-viewer
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}
          path: remote-viewer-${{ matrix.arch }}.tgz

  build-lnux:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform: [ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Install dependencies
        run: |
          docker run -v $(pwd):/v --entrypoint /bin/sh --name remote_viewer --platform linux/${{ matrix.arch }} ubuntu -c "apt update && \
          DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends tzdata  && \
          apt install -y wget libxml2-dev libglib2.0-dev libgtk-3-dev python3 python3-pip python3-setuptools python3-wheel && \
          pip3 install --user meson && \
          pip3 install --user ninja && \
          export PATH="/root/.local/bin:$PATH" && \
          wget https://gitlab.com/virt-viewer/virt-viewer/-/archive/v11.0/virt-viewer-v11.0.tar.gz && \
          tar -xzf virt-viewer-v11.0.tar.gz && \
          cd virt-viewer-v11.0 && \
          meson build -Dlibvirt=disabled -Dovirt=disabled -Dvte=disabled -Dbash_completion=disabled && \
          mkdir -p /usr/local/share/mime/packages && \
          chmod 0777 /usr/local/share/mime/packages && \
          cd build && \
          meson install && \
          wget https://github.com/NixOS/patchelf/releases/download/0.14.3/patchelf-0.14.3-$(uname -m).tar.gz && \
          tar -xzf patchelf-0.14.3-$(uname -m).tar.gz
          cp bin/patchelf /usr/bin/
          bash /v/fix_linux.sh ${{ matrix.arch }} && \
          tar cf remote-viewer-${{ matrix.arch }}.tgz libs src/remote-viewer"

          sudo docker cp remote_viewer:/virt-viewer-v11.0/build/remote-viewer-${{ matrix.arch }}.tgz .
          ls -l ./
      - name: Upload remote-viewer
        if: steps.cache-remote-viewer.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}
          path: remote-viewer-${{ matrix.arch }}.tgz