name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [amd64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: before
        run: |
          ls -lt /usr/local/lib
          sudo du -sh /usr/local 

      - name: Macports 0
        run: |
           wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
           sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /

      - name: Install dependencies
        run: |
          export PATH="/opt/local/bin:$PATH" 

          sudo port install glib2 libxml2 gtk3 gtk-vnc meson pkgconfig spice-gtk
          wget https://gitlab.com/virt-viewer/virt-viewer/-/archive/v11.0/virt-viewer-v11.0.tar.gz
          tar -xzf virt-viewer-v11.0.tar.gz
          cd virt-viewer-v11.0
          export PKG_CONFIG_PATH="/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig"
          meson build -Dlibvirt=disabled -Dovirt=disabled -Dvte=disabled -Dbash_completion=disabled -Dvnc=enabled -Dspice=enabled 
          cd build
          meson install
          pwd
          ls -l /opt/local/lib
          chmod +x ../../fix_mac.sh
          ../../fix_mac.sh

      - name: Compress remote-viewer
        run: |
          ./virt-viewer-v11.0/build/src/remote-viewer --version
          tar -czvf remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz virt-viewer-v11.0/build/share virt-viewer-v11.0/build/libs virt-viewer-v11.0/build/src/remote-viewer
      
      - name: Upload remote-viewer artifact
        uses: actions/upload-artifact@v2
        with:
          name: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}
          path: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz
          prerelease: true

  build-lnux:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform: [linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-qemu-action
        uses: docker/setup-qemu-action@v1

      - name: Install dependencies
        run: |
          docker run -v $(pwd):/v --entrypoint /bin/sh --name remote_viewer --platform linux/${{ matrix.arch }} fedora -c "dnf update -y && \
          dnf install -y findutils && \
          dnf install -y patchelf wget gtk-vnc2-devel spice-gtk-tools spice-glib-devel spice-gtk3-devel libxml2-devel glib2-devel gtk3-devel meson && \
          wget https://gitlab.com/virt-viewer/virt-viewer/-/archive/v11.0/virt-viewer-v11.0.tar.gz && \
          tar -xzf virt-viewer-v11.0.tar.gz && \
          cd virt-viewer-v11.0 && \
          meson build -Dlibvirt=disabled -Dovirt=disabled -Dvte=disabled -Dbash_completion=disabled -Dvnc=enabled -Dspice=enabled
          cd build && \
          meson install && \
          mkdir "bin" && \
          cp src/remote-viewer bin/ && \
          bash /v/fix_linux.sh ${{ matrix.arch }} && \
          tar -czvf remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz libs bin"

          sudo docker cp remote_viewer:/virt-viewer-v11.0/build/remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz .
          
      - name: Upload remote-viewer artifact
        uses: actions/upload-artifact@v2
        with:
          name: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}
          path: remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            remote-viewer-${{ matrix.platform }}-${{ matrix.arch }}.tgz
          prerelease: true
          