name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: before
        run: |
          ls -lt /usr/local
          du -sh /usr/local

      - name: Macports 0
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
           wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
           sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /

      - name: Install dependencies
        run: |
          export PATH="/opt/local/bin:$PATH" 

          sudo port install glib2-devel gtk3 meson
          wget https://gitlab.com/virt-viewer/virt-viewer/-/archive/v11.0/virt-viewer-v11.0.tar.gz
          tar -xzf virt-viewer-v11.0.tar.gz
          cd virt-viewer-v11.0
          export PKG_CONFIG_PATH="/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig"
          meson build
          cd build
          meson install

      - name: after
        run: |
          ls -lt /opt/local
          du -sh /opt/local
          ls -lt /usr/local
          du -sh /usr/local